### ISSUE TITLE
Credits?

### ISSUE THREAD

**Issue by RomRider** [Savjee/button-text-card#20]
I think when you copy chunks of code (without even taking the time to modify it to match your use case) it would be great to give some credits to the people who wrote it initially ;)

Also, why not share templates for button-card with the community instead of creating a whole new card for a specific purpose as I think (but I might be wrong) that everything you are doing can be achieved with button-card?

**Comment by Savjee** [comment]
What code did I copy without giving credit? Are you referring to the boilerplate template or to the template engine of button-card? I referenced both of them in the source code but I could add them to the README as well.

I haven't used button-card yet, but it seems like it might be possible to recreate this card. I did make my own plugin to maintain a uniform look across cards with minimal code. But again, I haven't used button-card.

**Comment by kenstone** [comment]
@RomRider Any additional comments on this? Can this issue be closed? Or what credits would you like to see added?

Personally, I don't doubt that this could be done with button-card, but I liked this project because it was simple to get going with the specific style rather than digging into button-card to make it do what I want.

**Comment by Savjee** [comment]
Closing for now...
